Product.create!([
  {name: "Prince Denesik", description: "Inventore quibusdam accusantium ut et.", price: "19.0", active: false},
  {name: "Dillan Fadel", description: "Sequi eaque perferendis id reiciendis ad dolor.", price: "2.0", active: false},
  {name: "Madie Durgan", description: "Explicabo quo ipsam error omnis vero.", price: "6.0", active: false},
  {name: "Dino Swaniawski DVM", description: "Ut ea omnis totam et amet.", price: "16.0", active: false},
  {name: "Jeremie Lynch", description: "Illum aut saepe eum.", price: "10.0", active: false},
  {name: "Daniela D'Amore", description: "Id voluptas suscipit voluptatem consequatur.", price: "10.0", active: false},
  {name: "Ross Buckridge MD", description: "Quo magni odit et reiciendis quia rerum.", price: "8.0", active: false},
  {name: "Aric Hodkiewicz", description: "Id sunt ex quos et.", price: "5.0", active: false},
  {name: "Raphael Gibson Sr.", description: "Id nemo deleniti qui.", price: "12.0", active: false},
  {name: "Jefferey Wolff", description: "Id et voluptatem pariatur tempora et in aliquid.", price: "0.0", active: false},
  {name: "Llewellyn Balistreri", description: "Placeat eos mollitia eum omnis qui quisquam doloremque.", price: "15.0", active: false},
  {name: "Torrance Leannon", description: "Et cumque autem possimus qui error quae ullam.", price: "8.0", active: false},
  {name: "Dr. Judge Raynor", description: "Fuga quis provident non deserunt voluptates beatae accusamus.", price: "5.0", active: false},
  {name: "Tony Renner IV", description: "Ratione dignissimos quo temporibus dolorem natus.", price: "17.0", active: false},
  {name: "Patience Krajcik", description: "Aut ipsum repudiandae illo culpa cum dicta et aut.", price: "10.0", active: false},
  {name: "Annabel Feil", description: "Et optio voluptatem asperiores accusantium.", price: "12.0", active: false},
  {name: "Leila Nienow IV", description: "Rerum est et praesentium voluptate tenetur.", price: "16.0", active: false},
  {name: "Ezequiel Jacobi Sr.", description: "Nihil inventore iste officia.", price: "15.0", active: false},
  {name: "Ms. Vena Considine", description: "Tenetur itaque similique suscipit perspiciatis ut non.", price: "8.0", active: false},
  {name: "Enrico Gusikowski PhD", description: "Qui quia officiis ut.", price: "9.0", active: false},
  {name: "Cale Emmerich", description: "Eligendi est odio eius autem.", price: "6.0", active: false},
  {name: "Angie Weber", description: "Qui soluta et est delectus aliquam.", price: "17.0", active: false},
  {name: "Evelyn Emmerich", description: "Quas ipsam id qui voluptas mollitia.", price: "2.0", active: false},
  {name: "Kaley Kerluke", description: "Accusantium ullam et qui.", price: "4.0", active: false},
  {name: "Eulalia Boehm", description: "Accusamus reiciendis dolore dignissimos magni distinctio praesentium suscipit.", price: "17.0", active: false},
  {name: "Stefan Hettinger", description: "Ipsam culpa eos sit.", price: "10.0", active: false},
  {name: "Dejon Nicolas", description: "Aliquid in id atque earum dolore voluptate.", price: "8.0", active: false},
  {name: "Horace Wilkinson", description: "Omnis similique debitis quia reiciendis aut provident a qui.", price: "19.0", active: false},
  {name: "Adonis Skiles I", description: "Aliquid in voluptatem reprehenderit enim numquam sit.", price: "0.0", active: false},
  {name: "Mrs. Vickie Keeling", description: "Corrupti excepturi aut fuga laboriosam reprehenderit.", price: "10.0", active: false},
  {name: "Imani Wiegand", description: "Molestiae officia et nam.", price: "19.0", active: false},
  {name: "River Farrell", description: "Quaerat eum id cum exercitationem neque suscipit ea consectetur.", price: "4.0", active: false},
  {name: "Miss Joelle Crist", description: "Autem eum accusamus placeat sint.", price: "0.0", active: false},
  {name: "Mitchell Hand", description: "Modi libero adipisci et.", price: "15.0", active: false},
  {name: "Miss Hardy Crist", description: "Asperiores rem ut sequi provident ratione alias.", price: "9.0", active: false},
  {name: "Hipolito Rutherford Jr.", description: "Est debitis maxime sed distinctio sit.", price: "8.0", active: false},
  {name: "Ms. Stefan Sanford", description: "Cupiditate ullam sunt eum eaque.", price: "2.0", active: false},
  {name: "Bertram Quigley", description: "Cupiditate unde cumque consequatur.", price: "5.0", active: false},
  {name: "Dr. Jarret Shields", description: "Deleniti assumenda omnis dolores.", price: "8.0", active: false},
  {name: "Abagail Bartoletti II", description: "Odio voluptatem consequatur dolores eius esse qui sint.", price: "15.0", active: false},
  {name: "Ms. Kamren Hegmann", description: "Qui a aut excepturi ratione maxime vitae.", price: "17.0", active: false},
  {name: "Mr. Alexzander Bosco", description: "Dolores quisquam quia quae maiores.", price: "19.0", active: false},
  {name: "Kamille Kling Jr.", description: "Praesentium eos at alias non quibusdam voluptas inventore impedit.", price: "4.0", active: false},
  {name: "Chad Bogisich", description: "Quae id quam architecto ad vitae.", price: "5.0", active: false},
  {name: "Elroy Turcotte Sr.", description: "Eaque fugit in aspernatur beatae accusantium dolores et quia.", price: "11.0", active: false},
  {name: "Dr. Rosa Graham", description: "Culpa sed voluptatem aut.", price: "15.0", active: false},
  {name: "Clovis Bartoletti", description: "Eius itaque dolorem et aut repellendus iure in vero.", price: "2.0", active: false},
  {name: "Mrs. Otilia Moen", description: "Qui iure consequatur nihil velit laborum tenetur exercitationem et.", price: "8.0", active: false},
  {name: "Jaylin Reinger", description: "Qui harum et omnis rem qui inventore.", price: "12.0", active: false},
  {name: "Howell Cronin", description: "Omnis blanditiis quisquam id dolorem at quia dignissimos eos.", price: "7.0", active: false},
  {name: "Mrs. Hanna Hammes", description: "Vel quae temporibus quas eum.", price: "0.0", active: false},
  {name: "Mr. Concepcion Bernhard", description: "Occaecati voluptatem quam deserunt vitae impedit.", price: "8.0", active: false},
  {name: "Muhammad Erdman", description: "Omnis accusantium et repudiandae dolores architecto ut autem.", price: "5.0", active: false},
  {name: "David Sanford", description: "Excepturi quis nihil asperiores.", price: "4.0", active: false},
  {name: "Leola Kautzer", description: "Voluptatibus et eius dolorem labore.", price: "0.0", active: false},
  {name: "Alisa Tromp PhD", description: "Consequatur quidem distinctio impedit eum a.", price: "9.0", active: false},
  {name: "Dorothy Maggio Jr.", description: "Suscipit quia ut quia labore aliquam porro qui et.", price: "0.0", active: false},
  {name: "Leonie Gulgowski", description: "Unde fugit omnis perspiciatis quis dignissimos sint aut dolorem.", price: "8.0", active: false},
  {name: "Alanis Renner", description: "Sunt odio porro ducimus.", price: "5.0", active: false},
  {name: "Zachary Cronin", description: "Quo sed incidunt eius quia quos.", price: "9.0", active: false},
  {name: "Mr. Treva O'Reilly", description: "Explicabo cum rerum fuga autem dicta possimus iusto.", price: "7.0", active: false},
  {name: "Myles Trantow", description: "Sit doloribus molestias cum non est.", price: "9.0", active: false},
  {name: "Cory Bartoletti", description: "Eos beatae ex dolore assumenda fugit incidunt nulla ut.", price: "10.0", active: false},
  {name: "Ella Hagenes IV", description: "Voluptatem sed totam sint et vitae.", price: "17.0", active: false},
  {name: "Nadia Steuber", description: "Dolorum vel quis ex temporibus culpa asperiores.", price: "4.0", active: false},
  {name: "Miss Grady Lindgren", description: "Non maiores vel quia.", price: "16.0", active: false},
  {name: "Ms. Jayne Altenwerth", description: "Totam itaque dignissimos delectus numquam id dolorem quia sit.", price: "16.0", active: false},
  {name: "Mrs. Salma Leannon", description: "Consequatur maxime et fugiat eos ut.", price: "13.0", active: false},
  {name: "Adolph Kemmer", description: "Placeat laborum est porro.", price: "18.0", active: false},
  {name: "Nickolas Grimes", description: "Natus possimus vel iste tempora sunt eos et quo.", price: "14.0", active: false},
  {name: "Lura Kertzmann", description: "Voluptatem itaque est eius illo.", price: "18.0", active: false},
  {name: "Camron Lind", description: "Ipsum odio qui veniam corporis earum debitis.", price: "3.0", active: false},
  {name: "Shania Treutel", description: "Enim vero ullam esse est impedit voluptate.", price: "18.0", active: false},
  {name: "Alexander Koch Sr.", description: "Dolore velit earum aliquam et nisi quo at fuga.", price: "13.0", active: false},
  {name: "Shanel Streich", description: "Consequatur adipisci unde at cum fugiat qui expedita.", price: "14.0", active: false},
  {name: "Raheem Emmerich", description: "Doloribus voluptatem a et quis id aspernatur.", price: "7.0", active: false},
  {name: "Fleta Ebert", description: "Hic illo id suscipit commodi et impedit.", price: "17.0", active: false},
  {name: "Lynn Feest", description: "Necessitatibus saepe quibusdam et quam est.", price: "12.0", active: false},
  {name: "Adah Beahan", description: "Dolorem est neque voluptas ut nobis cum.", price: "12.0", active: false},
  {name: "Robert Simonis", description: "Perferendis debitis non magni repellendus aliquam eum.", price: "10.0", active: false},
  {name: "Gudrun Hettinger", description: "Facere dicta ex eos maxime temporibus atque error sed.", price: "11.0", active: false},
  {name: "Jazlyn Lynch DVM", description: "Voluptatem explicabo in optio non qui.", price: "7.0", active: false},
  {name: "Miss Felipa Casper", description: "Ut maxime quos reprehenderit quia est omnis officiis.", price: "10.0", active: false},
  {name: "Autumn Abernathy", description: "Vero itaque ab soluta.", price: "12.0", active: false},
  {name: "Jonathon Morissette I", description: "Numquam labore sit qui ipsam rerum dolorem ab est.", price: "16.0", active: false},
  {name: "Samir Harvey", description: "Sit perferendis dolor ipsum minima.", price: "12.0", active: false},
  {name: "Aryanna Runolfsdottir", description: "Dolorum nihil adipisci esse in veritatis.", price: "8.0", active: false},
  {name: "Natalia Prohaska", description: "Enim adipisci velit commodi sed.", price: "3.0", active: false},
  {name: "Demario Donnelly", description: "Aliquam placeat deserunt adipisci.", price: "7.0", active: false},
  {name: "Lewis Bernhard", description: "Doloribus recusandae est corporis est molestiae accusamus.", price: "10.0", active: false},
  {name: "Emilie Willms", description: "Sit molestias cum labore soluta mollitia fugiat amet.", price: "2.0", active: false},
  {name: "Ramona Dicki", description: "Amet et et in minima architecto.", price: "16.0", active: false},
  {name: "Bridgette Stoltenberg", description: "Consequuntur rem totam doloribus dignissimos quasi distinctio non.", price: "17.0", active: false},
  {name: "Miss Devin Armstrong", description: "Et illum explicabo minima assumenda totam distinctio.", price: "4.0", active: false},
  {name: "Missouri Walker", description: "Qui velit libero maiores voluptatem repudiandae.", price: "17.0", active: false},
  {name: "Yoshiko Davis II", description: "Culpa reiciendis voluptatem ea error et ducimus.", price: "17.0", active: false},
  {name: "Megane Mante", description: "Eveniet sit assumenda eaque quidem.", price: "16.0", active: false},
  {name: "Triston Larson", description: "Architecto eos voluptatem sint ex est exercitationem.", price: "7.0", active: false},
  {name: "Augusta Ullrich", description: "Nam et et in.", price: "15.0", active: false},
  {name: "Sierra Pfannerstill", description: "Quidem molestias omnis architecto qui id dolor quam.", price: "11.0", active: false}
])
